### ISSUE TITLE
shouldn't FileAttr.{crtime,flags} be #[cfg(target_os = "macos")]?

### ISSUE THREAD

**Issue by vthriller** [zargony/rust-fuse#113]
I mean, why would some fs developer bother with faking something if it's going to be silently discarded on his non-macbook anyways?

It's also a good way to hint macOS devs that fields that they are going to use are not that portable after all.

**Comment by asomers** [comment]
If you go this route, don't forget to enable them for the BSDs, too.

**Comment by zargony** [comment]
I added cfg gates to `crtime` and `flags` of `FileAttr` in aab40c9 so that one doesn't have to bother with setting them on Linux where they get dropped anyway.

@asomers Unfortunately BSD testing is pretty bad right now (I don't have a BSD system to test manually and there's no CI support for BSD right now afaik). The current ABI (`fuse_attr`) has `crtime` and `flags` for macOS only, so they were dropped silently on BSD as well. If the BSD FUSE ABI differs from the Linux FUSE ABI (not sure, I thought it doesn't), we should probably remove mentioning BSD compatibility until someone jumps in to add / verify / maintain proper BSD support.

**Comment by asomers** [comment]
Actually, the current FreeBSD ABI is identical to the Linux ABI.  My comment of Oct-27 was a mistake.  Regarding FreeBSD compatibility, the tests currently all pass on FreeBSD.  Would you be interested in adding CI?  I could set it up for you.

**Comment by zargony** [comment]
I'm relieved to hear that. Although I don't use FreeBSD a lot, I was always happy to support FreeBSD and since its ABI is the same, it basically comes for free to support it.

Anyway, adding it to CI is probably a good idea. Thanks a lot for offering help! I'll create a new issue for it.
