### ISSUE TITLE
Read file using inode number

### ISSUE THREAD

**Issue by mb720** [zargony/rust-fuse#156]
Hi and thanks for fuse-rs!

I'd like to read the contents of a file using its inode number, basically reimplementing what [`debugfs`](https://www.kernel.org/doc/html/latest/filesystems/debugfs.html) does with the [`cat`](https://github.com/tytso/e2fsprogs/blob/7b8253ba09e635d328a48c98a184b571b809911b/debugfs/dump.c#L371) command:

    debugfs -R 'cat <8>' /dev/sda3

In this example, `/dev/sda3` has an ext4 file system.

I know that this create has [`read`](https://docs.rs/fuse/0.3.1/fuse/trait.Filesystem.html#method.read) but I'm not sure whether this method is suitable for my task.

How would I use `read` to get at the contents of a file using the file's inode number?

Thanks!

---

Using inode number 8 in the example above is not a coincidence: I want to read the [ext4 journal](https://www.kernel.org/doc/html/latest/filesystems/ext4/globals.html#journal-jbd2) with Rust.

**Comment by Minoru** [comment]
Hi! I think you're confusing a few things here.

The debugfs that you linked is a virtual filesystem that Linux kernel uses for debugging. It has no relationship to the `debugfs` binary that contains the `cat` command. Do not look at the docs for debugfs-the-filesystem, they are irrelevant.

The `read()` function that you linked is a part of a FUSE low-level interface, which is an interface between the kernel and your application. It gets called by the kernel when someone tries to read a file, but the inode is supplied by the kernel, based on your app's earlier response to `lookup()` function which converts paths to inodes. There is no way to directly call this `read()` from the userspace; you can only call things like [`open(2)`](https://www.man7.org/linux/man-pages/man2/open.2.html) and [`read(2)`](https://man7.org/linux/man-pages/man2/read.2.html) which the kernel then translates into calls to FUSE's `lookup()` and `read()`. 

Linux, and Unix-likes in general, don't provide an API to read a specific inode, [because Unix's permissions system relies on paths](https://stackoverflow.com/a/36092651/2350060).

If you want to read the ext4 journal, you have to open `/dev/sda3` as a binary file, find the offset at which the journal starts, and read that. Or maybe script over `debugfs`-the-tool to parse its output. I don't think FUSE, or this crate, can help you with any of that.

**Comment by mb720** [comment]
You're right, the link to `debugfs` should have been to the [tool](https://linux.die.net/man/8/debugfs).

Thank you for confirming that fuse-rs is probably not the right choice for my little undertaking.

My current leads are getting inspiration from `jls` (part of The Sleuth Kit) that uses the method [ext2fs_dinode_load](https://github.com/sleuthkit/sleuthkit/blob/ef6fcaa7dd702d96785d590acc6fc97d76b4723f/tsk/fs/ext2fs.c#L460) to get at the file contents and `cat` from `debugfs` which calls [`dump_file`](https://github.com/tytso/e2fsprogs/blob/7b8253ba09e635d328a48c98a184b571b809911b/debugfs/dump.c#L100).
