### ISSUE TITLE
Is x86_64-unknown-linux-musl unsupported for reason or just because of platform detection is lacky?

### ISSUE THREAD

**Issue by vi** [zargony/rust-fuse#62]
```
$ cargo test --target=x86_64-unknown-linux-musl
Build failed, waiting for other jobs to finish...
failed to run custom build command for `fuse v0.2.7`
Process didn't exit successfully: `/home/vi/code/outoforderfs/target/debug/build/fuse-5faebf645a751bfb/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'Unsupported target platform', /home/vi/.multirust/toolchains/nightly/cargo/registry/src/github.com-48ad6e4054423464/fuse-0.2.7/build.rs:15
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
build.rs>  else if target.ends_with("-unknown-linux-gnu") || target.ends_with("-unknown-freebsd")
```

**Comment by cuviper** [comment]
I'll bet that code just predates musl support in Rust, and no one has cared
yet. It will probably just work to add musl next to linux-gnu. The other
BSD variants are missing too, but I wouldn't suggest adding them until
someone is available to try it.

**Comment by zargony** [comment]
I also think nobody has cared to try yet. In the latest version, the build script was modified to not depend on specific target triples, but to simply use pkg-config. So it should also work with musl now.

I'm closing this since the reported panic condition doesn't exist anymore. Please reopen if this is still an issue (I tried to run rustc on alpine in a Docker container, but couldn't get it to run the easy way)
