### ISSUE TITLE
BackgroundSession does not stop filesystem thread on OS X

### ISSUE THREAD

**Issue by MicahChalmer** [zargony/rust-fuse#7]
If you create a `BackgroundSession` object and destroy it, the background task running the real session won't actually terminate right away on OS X.  It seems that the `libc::read` call is not interrupted by the call to `fuse_unmount_compat22`, so it won't kill the background task until something else tries to use the filesystem.  Unmounting it externally (by running "umount" in another shell) does not appear to have this problem--it interrupts the read call right away.  The problem also doesn't seem to happen on Linux.

**Comment by mciantyre** [comment]
I'm sorry to bring up a four year old issue, but I feel it may be related to an issue I'm experiencing. After dropping a `BackgroundSession`, I am unable to remount a filesystem at the same mountpoint. I get the error

```
fuse: attempt to remount on active mount point: /path/to/the/mount/point
```

from FUSE. I'm running macOS 10.13 and osxfuse 3.7.1. I can show that the same issue is not present when running on a Linux system.

I created a test [here](https://github.com/mciantyre/rust-fuse/blob/master/tests/background_session_unmount.rs) to demonstrate the behavior. Essentially, I took the `hello.rs` example filesystem, mount it using `spawn_mount` to get a `BackgroundSession`, and try to read the `hello.txt` file. I let the `BackgroundSession` drop, then I try again after a 1 second delay.

We might expect the filesystem to unmount and remount successfully. However, the test seems to demonstrate that remounting the filesystem at the same mountpoint throws an error. Compiling and running the same test on Linux passes.

```
git clone git@github.com:mciantyre/rust-fuse.git
cd rust-fuse
cargo test -- --test-threads 1
```

Could this be because the `BackgroundSession` isn't stopping the filesystem thread on macOS? I noticed the TODO in the `impl Drop for Channel` implementation, and I might try to address it if we feel it's related. Or, am I trying to do something that FUSE and this library can't support?

Thanks for your help and for this great library!
