### ISSUE TITLE
time::Timespec or std::time::SystemTime (fuse::FileAttr)

### ISSUE THREAD

**Issue by alilee** [zargony/rust-fuse#87]
Would it be a good idea to patch to this? That would be a breaking change to fuse::FileAttr.

(The need would be reduced significantly if Timespec implemented From<SystemTime>)

**Comment by zargony** [comment]
I like this, especially because the time crate seems to be deprecated now that std has some time types. However it seems to be hard to construct a SystemTime from arbitrary values (like time_t integer values) and most filesystem implementations probably store some kind of integer for timestamps. Maybe we could use std::sys::unix::time::SystemTime directly instead (not sure about this, I'm not very familiar with std::time and just had a quick look to the source)

**Comment by alilee** [comment]
That's the ugly part - but it probably optimises away ok. Here's going backward with duration_since:
```rust
fn timespec_from(st: &SystemTime) -> Timespec {
    if let Ok(dur_since_epoch) = st.duration_since(std::time::UNIX_EPOCH) {
        Timespec::new(dur_since_epoch.as_secs() as i64,
                      dur_since_epoch.subsec_nanos() as i32)
    } else {
        Timespec::new(0, 0)
    }
}
```

**Comment by acheronfail** [comment]
@zargony I'd like to work on this, since I want to remove the dependency on the deprecated `time` crate. Do you have any suggestions on a possible solution?

I tried replacing all `Timespec` with `std::time::Duration` structs, and surprisingly enough all the tests still passed! [See the diff here](https://github.com/zargony/rust-fuse/compare/master...acheronfail:remove-deprecated-time-crate?expand=1).

^^ Although, it's not the best solution since it involves a lot of casting between `i64` and `u64`, etc. 

More than happy to work on this, any pointers for me? :slightly_smiling_face:

**Comment by zargony** [comment]
Looks good to me. I like the idea to get rid of the `time` crate. As far as I remember, there was no `std::time` back when these structs were created.

`Duration` however doesn't sound right to me. As far as I know, `Duration` is meant to measure a period of time rather than a point in time which we need here. `std::fs::Metadata` uses `std::time::SystemTime` therefore (which actually wraps a `Duration`, but has a different semantic meaning).
(This reminds me of the idea that we should actually have a low-level and a high-level interface like libfuse provides.)

Also it would be nice to keep the file information statically in the hello example (it was meant to show its simplicity). But we can't express a static time yet in stable Rust, right? (does stable Rust have const fns already?)

I wonder why the atime/mtime/ctime fields are signed anyway. Looking at the original fuse_kernel.h makes me think this should be actually unsigned integers.

**Comment by acheronfail** [comment]
>  As far as I know, Duration is meant to measure a period of time rather than a point in time which we need here. std::fs::Metadata uses std::time::SystemTime therefore (which actually wraps a Duration, but has a different semantic meaning).

I agree with that. I haven't used `SystemTime` before, but it seems it doesn't expose a way to pull out the seconds and nanoseconds unless you convert it to a `Duration` first... I'll look into it.

> Also it would be nice to keep the file information statically in the hello example (it was meant to show its simplicity). But we can't express a static time yet in stable Rust, right? (does stable Rust have const fns already?)

I know, that was the part I disliked the most. Rust doesn't have const fns yet, no. (At least not in stable).

> I wonder why the atime/mtime/ctime fields are signed anyway. Looking at the original fuse_kernel.h makes me think this should be actually unsigned integers.

I was actually confused by this as well!
Surely we should just convert them all to unsigned integers? I can't think of a reason why we'd need them to be signed.
